import Head from "next/head";
import styled from "styled-components";

const StyledMain = styled.main`
  background: red;
  height: 100%;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>Hello world</StyledMain>
    </>
  );
}
